### PR TITLE
Revert ms-rest in package.json to previous version

### PR DESCRIPTION
**Pull request by BillZengMSFT**

### CODE REVIEW

**Comment by jingjingxia** [comment]
Who made the version bump in the first place? Do we need to revert other associated changes together with this?

**Comment by bilby91** [comment]
@BillZengMSFT What was the issue with the ms-rest bump ?

**Comment by BillZengMSFT** [comment]
@bilby91 this change will require promise library but it is not what we are using for now.

**Comment by bilby91** [comment]
Thanks for the data @BillZengMSFT !

**Pull request merged**
