### PR TITLE
Add support for Azure Functions (Node)

### PR DESCRIPTION
**Pull request by iMicknl**
The TeamsChatConnector isn't ready for use with Azure Functions. I merged the Azure Functions specific code from [BotBuilder Azure](https://github.com/Microsoft/BotBuilder-Azure/) to the TeamsChatConnector, which works like a charm.

You can setup the function using ```module.exports = connector.listen();```.

**Concerns**

1. Should this be a seperate ChatConnector or be merged into the main chat connector? ([example](https://gist.github.com/iMicknl/dbcd42ee5d99bda86b1dbce6c6e442a1))

2. No official typings available for Azure Functions, leave them out or use [this unofficial package](https://github.com/christopheranderson/azure-functions-typescript)?

### CODE REVIEW

**Comment by iMicknl** [comment]
Any update? Would be nice if this package also supported Azure Functions. @BillZengMSFT

**Comment by RamjotSingh** [comment]
@aosolis @BillZengMSFT Please review

**Comment by BillZengMSFT** [comment]
@iMicknl  thanks for contribution. I will discuss with our PM.

**Comment by RamjotSingh** [comment]
@BillZengMSFT Are we planning to take this PR? Otherwise we should close it :)

**Comment by aosolis** [comment]
I took a look, and compared it with what's in BotBuilder-Azure. It's fairly straightforward, however, I think this should be a separate connector derived from TeamsChatConnector. It looks like the changes will break the connector when used outside the Azure Functions context.

**Comment by RamjotSingh** [comment]
Based on @aosolis 's comments. Closing this PR.

**Pull request closed without merging**
